// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBTest.Models;

namespace WEBCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200319011440_MyFristMigration2")]
    partial class MyFristMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEBCore.Models.Firend", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fid");

                    b.Property<int>("uid");

                    b.HasKey("id");

                    b.HasIndex("uid");

                    b.ToTable("Firend");
                });

            modelBuilder.Entity("WEBTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account");

                    b.Property<string>("address");

                    b.Property<string>("emial");

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WEBCore.Models.Firend", b =>
                {
                    b.HasOne("WEBTest.Models.User", "user")
                        .WithMany("Firend")
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
